# Generated by Django 3.1.7 on 2021-04-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210402_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BigCategory',
            new_name='Brand',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bigCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        ),
    ]
